"""Add fiscal settings

Revision ID: a7920be705d8
Revises: dee4c5d876f9
Create Date: 2025-12-23 16:57:21.935903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7920be705d8'
down_revision: Union[str, Sequence[str], None] = 'dee4c5d876f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_siret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('settings', sa.Column('is_vat_applicable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('settings', sa.Column('vat_exemption_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='TVA non applicable, art. 293 B du CGI'))
    op.add_column('settings', sa.Column('late_payment_penalties', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="3 fois le taux d'intérêt légal"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'late_payment_penalties')
    op.drop_column('settings', 'vat_exemption_text')
    op.drop_column('settings', 'is_vat_applicable')
    op.drop_column('settings', 'company_siret')
    # ### end Alembic commands ###
