"""add_deposit_fields

Revision ID: add_deposit_fields
Revises: eb5e685c0191
Create Date: 2025-12-24 15:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_deposit_fields"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote",
        sa.Column("deposit_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "quote",
        sa.Column("deposit_amount", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote", "deposit_amount")
    op.drop_column("quote", "deposit_percentage")
    # ### end Alembic commands ###
