"""add_detailed_description

Revision ID: add_detailed_description
Revises: add_deposit_fields
Create Date: 2025-12-24 16:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_detailed_description"
down_revision: Union[str, Sequence[str], None] = "add_deposit_fields"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote_item",
        sa.Column("detailed_description", sa.TEXT(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_item", "detailed_description")
    # ### end Alembic commands ###
