"""add settings table

Revision ID: dee4c5d876f9
Revises: c2cef7f26801
Create Date: 2025-12-23 12:46:46.302930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dee4c5d876f9'
down_revision: Union[str, Sequence[str], None] = 'c2cef7f26801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_footer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_tax_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
