"""add_tax_fields

Revision ID: eb5e685c0191
Revises: update_quote_status_enum
Create Date: 2025-12-24 14:48:40.642811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb5e685c0191'
down_revision: Union[str, Sequence[str], None] = 'update_quote_status_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('tax_status', sa.Enum('FRANCHISE', 'ASSUJETTI', name='taxstatus'), nullable=False))
    op.add_column('quote', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('quote', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.alter_column('quote', 'share_token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('quote', 'signed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('quote', 'signature_data',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('user', sa.Column('siret', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('tax_status', sa.Enum('FRANCHISE', 'ASSUJETTI', name='taxstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tax_status')
    op.drop_column('user', 'address')
    op.drop_column('user', 'siret')
    op.alter_column('quote', 'signature_data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quote', 'signed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('quote', 'share_token_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('quote', 'payment_date')
    op.drop_column('quote', 'is_paid')
    op.drop_column('quote', 'tax_status')
    # ### end Alembic commands ###
